import type { School, MatrixRow, PairKey, SchoolSlug } from './types'

export const SCHOOL_ORDER: SchoolSlug[] = [
  'nyaya', 'vaisheshika', 'samkhya', 'yoga', 'mimamsa', 'vedanta',
]

export const PAIRS: PairKey[] = [
  'nyaya-vaisheshika',
  'samkhya-yoga',
  'mimamsa-vedanta',
]

export const PAIR_MAP: Record<PairKey, [SchoolSlug, SchoolSlug]> = {
  'nyaya-vaisheshika': ['nyaya', 'vaisheshika'],
  'samkhya-yoga':      ['samkhya', 'yoga'],
  'mimamsa-vedanta':   ['mimamsa', 'vedanta'],
}

export const PAIR_COLOR: Record<PairKey, string> = {
  'nyaya-vaisheshika': '#2D7A6F',
  'samkhya-yoga':      '#5B4A8A',
  'mimamsa-vedanta':   '#C07828',
}

export const PAIR_BG: Record<PairKey, string> = {
  'nyaya-vaisheshika': 'bg-teal-50',
  'samkhya-yoga':      'bg-purple-50',
  'mimamsa-vedanta':   'bg-saffron-50',
}

export const PAIR_LABEL: Record<PairKey, string> = {
  'nyaya-vaisheshika': 'Nyāya · Vaiśeṣika',
  'samkhya-yoga':      'Sāṃkhya · Yoga',
  'mimamsa-vedanta':   'Mīmāṃsā · Vedānta',
}

export const SCHOOLS: School[] = [
  {
    slug: 'nyaya',
    pair: 'nyaya-vaisheshika',
    name: 'Nyāya',
    devanagari: 'न्याय',
    sanskrit: 'Nyāya',
    sutraText: 'pramāṇair arthāparikṣā nyāyaḥ',
    sutraDevanagari: 'प्रमाणैरर्थपरीक्षा न्यायः',
    sutraSource: 'Nyāya Sūtra 1.1.1 — Gautama',
    tagline: 'Logic and valid knowledge',
    identity: 'Nyāya is the school of correct reasoning. It establishes four pramāṇas — perception, inference, comparison, and testimony — as the instruments for valid knowledge. Liberation is achieved by correct cognition dispelling false knowledge.',
    epistemology: 'Four pramāṇas: pratyakṣa (perception), anumāna (inference), upamāna (comparison), śabda (testimony). Knowledge of the self is achieved through inference.',
    ontology: 'Accepts 16 padārthas (categories of reality). God (Īśvara) is the efficient cause of the universe. The individual self (ātman) is a real, permanent entity distinct from body and mind.',
    soteriology: 'Liberation (apavarga) is the absolute cessation of pain — not positive bliss but the elimination of misery through correct knowledge that removes false identification with the body.',
    tenets: [
      { label: 'Pramāṇa', body: 'Valid knowledge is grounded in four sources: perception, inference, comparison, and testimony. Without valid pramāṇas there is no reliable path to any truth.' },
      { label: 'Anumāna', body: 'Inference proceeds through five-membered syllogism (pañcāvayava): pratijñā (thesis), hetu (reason), udāharaṇa (example), upanaya (application), nigamana (conclusion).' },
      { label: 'Ātman', body: 'The self is a real, permanent substance — distinct from body, sense organs, and mind. It is the locus of consciousness, desire, and volition.' },
      { label: 'Īśvara', body: 'God is the intelligent efficient cause of creation, not the material cause. He coordinates the combination of atoms into a universe in accordance with karma.' },
      { label: 'Apavarga', body: 'Liberation is the complete cessation of pain and rebirth. It is a negative state — the removal of false identification — not positive bliss (ānanda).' },
      { label: 'Hetvābhāsa', body: 'The Nyāya school catalogues fallacious reasoning (hetvābhāsa) systematically: inconclusive, contradictory, equal to the question, unproven, and mistimed reasons.' },
    ],
    commentators: [
      { name: 'Vātsyāyana', period: '~4th–5th c. CE', work: 'Nyāya Bhāṣya', note: 'The primary commentary on Nyāya Sūtras — establishes the 16 padārtha framework and refutes Buddhist and Cārvāka objections.' },
      { name: 'Uddyotakara', period: '~6th c. CE', work: 'Nyāyavārttika', note: 'Defends Nyāya against Dignāga\'s Buddhist logic; sharpens the anumāna doctrine.' },
      { name: 'Vācaspati Miśra', period: '~9th c. CE', work: 'Nyāyavārttikatātparyaṭīkā', note: 'Encyclopaedic synthesis across all six darśanas; clarifies the theory of inference.' },
      { name: 'Udayana', period: '~10th c. CE', work: 'Nyāyakusumāñjali', note: 'Definitive theistic argument for Īśvara\'s existence — the Nyāya "cosmological argument."' },
    ],
    pairNote: 'Nyāya provides the epistemological and logical scaffolding; Vaiśeṣika provides the ontological categories. The schools merged into Navya-Nyāya by the 10th century.',
  },
  {
    slug: 'vaisheshika',
    pair: 'nyaya-vaisheshika',
    name: 'Vaiśeṣika',
    devanagari: 'वैशेषिक',
    sanskrit: 'Vaiśeṣika',
    sutraText: 'dharmaviśeṣaprasūtād dravyaguṇakarmāṇi',
    sutraDevanagari: 'धर्मविशेषप्रसूताद् द्रव्यगुणकर्माणि',
    sutraSource: 'Vaiśeṣika Sūtra 1.1.4 — Kaṇāda',
    tagline: 'Atomism and ontological categories',
    identity: 'Vaiśeṣika is the school of particulars (viśeṣa). It analyses the world into seven fundamental categories and posits that all physical objects are composed of eternal, indivisible atoms (paramāṇu).',
    epistemology: 'Accepts two pramāṇas: perception and inference. Does not accept upamāna or śabda as independent sources, placing it in a more empiricist tradition than Nyāya.',
    ontology: 'Seven padārthas (categories): dravya (substance), guṇa (quality), karma (action), sāmānya (universal), viśeṣa (particular), samavāya (inherence), abhāva (absence). Nine types of substance including earth, water, fire, air, ether, time, space, self, and mind.',
    soteriology: 'Liberation arises from correct knowledge of the padārthas, dissolving false identification with the body-mind complex. The self rests in pure, cognitionless existence at liberation.',
    tenets: [
      { label: 'Paramāṇu', body: 'The smallest, indivisible unit of matter. Atoms are eternal and qualitatively distinct — earth atoms differ from water atoms by their inherent qualities.' },
      { label: 'Saptapadārtha', body: 'Reality is classified into seven categories: substance, quality, action, universal, particular, inherence, and absence. Every knowable thing falls under one.' },
      { label: 'Viśeṣa', body: 'The ultimate particularity — that which makes each eternal substance (atom, self, etc.) irreducibly distinct from all others. The school is named after this category.' },
      { label: 'Samavāya', body: 'The eternal, inseparable relation between inhering and substrate: quality inheres in substance, universal in particulars. Distinct from mere conjunction (saṃyoga).' },
      { label: 'Adrṣṭa', body: 'The unseen moral force — accumulated from dharma/adharma — that explains atomic combination into ordered wholes and the cosmic processes between destruction and creation.' },
      { label: 'Dvyaṇuka', body: 'The first compound produced by two atoms. When two paramāṇus combine under adrṣṭa they form a dvyaṇuka; three dvyaṇukas form a tryaṇuka — and so scales up to perceptible size.' },
    ],
    commentators: [
      { name: 'Praśastapāda', period: '~5th–6th c. CE', work: 'Padārthadharmasaṃgraha', note: 'The most important Vaiśeṣika text after the sūtras — a systematic reconstruction rather than strict commentary.' },
      { name: 'Śrīdhara', period: '~10th c. CE', work: 'Nyāyakandalī', note: 'Commentary on Praśastapāda; clear exposition of the atomic theory and the seven padārthas.' },
      { name: 'Udayana', period: '~10th c. CE', work: 'Kiraṇāvalī', note: 'Bridges Nyāya and Vaiśeṣika into the unified Nyāya-Vaiśeṣika school; argues for God as cosmic coordinator of atoms.' },
    ],
    pairNote: 'Vaiśeṣika provides the ontological map of reality; Nyāya provides the logical method for knowing it. Their merger into Navya-Nyāya was intellectually productive and historically decisive.',
  },
  {
    slug: 'samkhya',
    pair: 'samkhya-yoga',
    name: 'Sāṃkhya',
    devanagari: 'सांख्य',
    sanskrit: 'Sāṃkhya',
    sutraText: 'duḥkhatrayābhighātāj jijñāsā tadabhighātake hetau',
    sutraDevanagari: 'दुःखत्रयाभिघाताज्जिज्ञासा तदभिघातके हेतौ',
    sutraSource: 'Sāṃkhya Kārikā 1 — Īśvarakṛṣṇa',
    tagline: 'Enumeration of cosmic principles',
    identity: 'Sāṃkhya is the school of enumeration. It posits two ultimate realities: Puruṣa (pure consciousness, plural) and Prakṛti (primal matter, singular). All suffering arises from their false identification; liberation is their discriminative separation.',
    epistemology: 'Three pramāṇas: perception, inference, and reliable testimony (āptavacana). The Sāṃkhya-Kārikā makes inference central — the existence of Prakṛti and Puruṣa are inferred, not perceived.',
    ontology: 'Twenty-five tattvas: Prakṛti → Mahat/Buddhi → Ahaṃkāra → 5 tanmātras + 5 jñānendriyas + 5 karmendriyas + manas → 5 bhūtas. Puruṣa is the 25th — pure consciousness beyond the Prakṛti hierarchy.',
    soteriology: 'Kaivalya — isolation of Puruṣa from Prakṛti. Liberation is not union with God (Sāṃkhya is explicitly atheistic in classical form) but discriminative knowledge (vivekajñāna) that ends Puruṣa\'s false identification with Prakṛti\'s productions.',
    tenets: [
      { label: 'Dvaitavāda', body: 'Reality is dualistic: consciousness (Puruṣa) and matter (Prakṛti) are eternally and ontologically distinct. Neither is reducible to the other.' },
      { label: 'Triguṇa', body: 'Prakṛti and all its derivatives are composed of three guṇas in varying proportion: sattva (clarity, luminosity), rajas (activity, passion), tamas (inertia, obscuration).' },
      { label: 'Satkāryavāda', body: 'The effect pre-exists in the cause (pariṇāmavāda form). Modification is real transformation, not mere appearance — the world evolves from Prakṛti, not from nothing.' },
      { label: 'Vivekajñāna', body: 'Liberation through discriminative knowledge: clearly seeing that Puruṣa is eternal, inactive witness and Prakṛti is the entire domain of activity, thought, and matter.' },
      { label: 'Puruṣabahutva', body: 'There are many Puruṣas (plural pure consciousnesses), not one. This distinguishes Sāṃkhya from Advaita Vedānta and explains the diversity of individual liberation.' },
      { label: 'Nirīśvara', body: 'Classical Sāṃkhya does not posit a God (Īśvara). The universe evolves from Prakṛti alone through the proximity of Puruṣa — no creator deity is required or admitted.' },
    ],
    commentators: [
      { name: 'Īśvarakṛṣṇa', period: '~3rd–4th c. CE', work: 'Sāṃkhya Kārikā', note: 'The foundational 72-verse text of classical Sāṃkhya — the Kārikā displaced all earlier texts and became the school\'s canonical statement.' },
      { name: 'Gauḍapāda', period: '~6th c. CE', work: 'Sāṃkhyakārikābhāṣya', note: 'Commentary on the Kārikā; clarifies the 25-tattva schema and the triguṇa doctrine.' },
      { name: 'Vācaspati Miśra', period: '~9th c. CE', work: 'Sāṃkhyatattvakaumudī', note: 'The most studied commentary on the Kārikā; systematic defence against Vedāntic absorption of Sāṃkhya.' },
    ],
    pairNote: 'Sāṃkhya provides the metaphysical map (25 tattvas, three guṇas, Puruṣa-Prakṛti dualism); Yoga takes this map as its philosophical basis and asks: how do we actually achieve the separation in practice?',
  },
  {
    slug: 'yoga',
    pair: 'samkhya-yoga',
    name: 'Yoga',
    devanagari: 'योग',
    sanskrit: 'Yoga',
    sutraText: 'yogaś citta-vṛtti-nirodhaḥ',
    sutraDevanagari: 'योगश्चित्तवृत्तिनिरोधः',
    sutraSource: 'Yoga Sūtra 1.2 — Patañjali',
    tagline: 'Cessation of mental fluctuations',
    identity: 'Yoga (Pātañjala Yoga / Rāja Yoga) is the school of mental discipline. It accepts Sāṃkhya metaphysics but adds Īśvara as a special Puruṣa — a meditation object — and provides the eight-limbed path (aṣṭāṅga) for achieving citta-vṛtti-nirodha.',
    epistemology: 'Three pramāṇas: direct perception, inference, and verbal testimony. The Yoga school emphasises pratyakṣa through meditative experience — the highest knowledge is the vivekakhyāti that arises in samādhi.',
    ontology: 'Accepts Sāṃkhya\'s 25 tattvas and adds Īśvara — a special, eternal Puruṣa untouched by kleśas, karma, and vipāka. Prakṛti\'s evolution is shaped by both the proximity of Puruṣas and the omniscient Īśvara.',
    soteriology: 'Kaivalya through citta-vṛtti-nirodha. The eight limbs (yama, niyama, āsana, prāṇāyāma, pratyāhāra, dhāraṇā, dhyāna, samādhi) progressively stabilise the mind until discriminative wisdom (vivekakhyāti) arises spontaneously.',
    tenets: [
      { label: 'Citta-vṛtti-nirodha', body: 'Yoga is the cessation of the fluctuations of the mind-field (citta). When these fluctuations cease, Puruṣa rests in its own nature; when they arise, it identifies with them.' },
      { label: 'Aṣṭāṅga', body: 'The eight-limbed path: yama (restraints), niyama (observances), āsana (posture), prāṇāyāma (breath regulation), pratyāhāra (sense withdrawal), dhāraṇā (concentration), dhyāna (meditation), samādhi (absorption).' },
      { label: 'Kleśa', body: 'Five afflictions root suffering: avidyā (ignorance), asmitā (ego), rāga (attachment), dveṣa (aversion), abhiniveśa (clinging to life). Avidyā — false identification — is the root of all others.' },
      { label: 'Samādhi', body: 'The final stage of dhāraṇā-dhyāna-samādhi (saṃyama) — the mind becomes transparent to its object. Samprajñāta samādhi still has object-support; asamprajñāta is objectless and leads to kaivalya.' },
      { label: 'Īśvara Praṇidhāna', body: 'Surrender to Īśvara is one of the five niyamas and a special accelerant to samādhi. Īśvara, as untouched Puruṣa, is the teacher of all teachers (guru of gurus) across time.' },
      { label: 'Vivekakhyāti', body: 'Discriminative wisdom — the culminating insight that Puruṣa is the eternal seer and Prakṛti (including intellect and ego) is the seen. This wisdom, when sustained, brings kaivalya.' },
    ],
    commentators: [
      { name: 'Vyāsa', period: '~4th–5th c. CE', work: 'Yogabhāṣya', note: 'The primary commentary on the Yoga Sūtras — its authority is nearly as high as Patañjali\'s own. Defines the five levels of citta.' },
      { name: 'Vācaspati Miśra', period: '~9th c. CE', work: 'Tattvavaiśāradī', note: 'Sub-commentary on Vyāsa\'s Bhāṣya — precise and philosophically systematic, clarifying technical terms.' },
      { name: 'Vijñānabhikṣu', period: '~16th c. CE', work: 'Yogavārttika', note: 'Integrates Yoga with Vedānta; argues Sāṃkhya-Yoga is not atheistic but theistically grounded.' },
      { name: 'Śaṅkarācārya', period: '~8th c. CE', work: 'Vivaraṇa (attrib.)', note: 'Attributed commentary — important for showing Advaita Vedānta\'s engagement with Yoga epistemology.' },
    ],
    pairNote: 'Sāṃkhya and Yoga are described as "one, seen by the learned" in the Bhagavad Gītā. Sāṃkhya is the theory; Yoga is the practice. They share metaphysics but diverge on Īśvara and method.',
  },
  {
    slug: 'mimamsa',
    pair: 'mimamsa-vedanta',
    name: 'Mīmāṃsā',
    devanagari: 'मीमांसा',
    sanskrit: 'Mīmāṃsā',
    sutraText: 'athāto dharmajijñāsā',
    sutraDevanagari: 'अथातो धर्मजिज्ञासा',
    sutraSource: 'Mīmāṃsā Sūtra 1.1.1 — Jaimini',
    tagline: 'Ritual exegesis and Vedic authority',
    identity: 'Mīmāṃsā (Pūrva Mīmāṃsā) is the school of Vedic exegesis. It holds that the Veda is eternal, authorless (apauruṣeya), and self-validating. The primary concern is dharma — what ought to be done — as determined by correct interpretation of Vedic injunctions.',
    epistemology: 'Six pramāṇas: the most of any school. Perception, inference, comparison, verbal testimony, postulation (arthāpatti), and non-cognition (anupalabdhi). The addition of arthāpatti and anupalabdhi reflects Mīmāṃsā\'s commitment to exhaustive epistemological coverage.',
    ontology: 'The world is real and pluralistic. Accepts eternal atoms, souls, and the Veda itself as eternal. Notably does not require a creator God — the Veda is self-existent and its authority is intrinsic, not derived from any author.',
    soteriology: 'Classical Mīmāṃsā is primarily concerned with dharma and ritual efficacy, not with liberation as such. Later Mīmāṃsā (Prabhākara, Kumārila) develops theories of svarga (heaven) and eventually apavarga, but ritual performance for its own sake remains central.',
    tenets: [
      { label: 'Apauruṣeyatva', body: 'The Veda is not authored by any person, human or divine. It is eternal, self-existing, and self-validating. Its authority is intrinsic (svataḥprāmāṇya), not derived from trust in an author.' },
      { label: 'Svataḥprāmāṇya', body: 'All knowledge is self-validating (intrinsically valid). Doubt and invalidation require external cause; validity does not. This is the Mīmāṃsā counter to Nyāya\'s parata-prāmāṇya.' },
      { label: 'Śabdanityatva', body: 'Sound (śabda) is eternal. The letters of the Veda are not produced by any speaker but are eternal entities that speakers merely manifest. This grounds the permanence of Vedic injunctions.' },
      { label: 'Dharma as codanā', body: 'Dharma is that which is indicated by Vedic injunction (codanā). It is not natural law or social convention but the commands of the Veda — primarily the vidhis (injunctions) and niṣedhas (prohibitions).' },
      { label: 'Arthāpatti', body: 'Postulation: knowledge inferred to explain an otherwise unexplained fact. If Devadatta is alive but not at home, he must be outside. This pramāṇa covers cases where perception and inference are insufficient.' },
      { label: 'Anityatva', body: 'No denial of impermanence at the level of the individual self — Mīmāṃsā accepts the eternality of the self but focuses exegetical energy on ritual consequence, not metaphysical liberation.' },
    ],
    commentators: [
      { name: 'Śabara', period: '~1st–3rd c. CE', work: 'Śābarabhāṣya', note: 'The foundational commentary — quotes lost texts and defines the central concepts of codanā, dharma, and Vedic interpretation.' },
      { name: 'Kumārila Bhaṭṭa', period: '~7th c. CE', work: 'Ślokavārttika', note: 'The Bhaṭṭa school\'s founder; vigorous defence of svataḥprāmāṇya and Vedic authority against Buddhist epistemology.' },
      { name: 'Prabhākara Miśra', period: '~7th c. CE', work: 'Bṛhatī', note: 'Founder of the rival Prābhākara school; differs on theory of error (akhyāti vs. viparīta-khyāti) and on the nature of validity.' },
      { name: 'Maṇḍana Miśra', period: '~8th c. CE', work: 'Bhāvanāviveka', note: 'Bridge figure between Mīmāṃsā and Advaita Vedānta; associated with Śaṅkara\'s debates.' },
    ],
    pairNote: 'Mīmāṃsā (Pūrva, "earlier") focuses on the karmakāṇḍa — the ritual portions of the Veda. Vedānta (Uttara, "later") focuses on the jñānakāṇḍa — the Upaniṣads. They share Vedic authority but pursue entirely different ends.',
  },
  {
    slug: 'vedanta',
    pair: 'mimamsa-vedanta',
    name: 'Vedānta',
    devanagari: 'वेदान्त',
    sanskrit: 'Vedānta',
    sutraText: 'athāto brahmajijñāsā',
    sutraDevanagari: 'अथातो ब्रह्मजिज्ञासा',
    sutraSource: 'Brahma Sūtra 1.1.1 — Bādarāyaṇa',
    tagline: 'Enquiry into Brahman',
    identity: 'Vedānta (Uttara Mīmāṃsā) is the school of Brahman-enquiry. Grounded in the Upaniṣads, Brahma Sūtras, and Bhagavad Gītā (the prasthānatrayī), it asks: what is the ultimate nature of Brahman, the self, and their relation? The three main sub-schools — Advaita, Viśiṣṭādvaita, Dvaita — differ on this relation.',
    epistemology: 'Three pramāṇas: perception, inference, and śabda (Vedic testimony). Śabda is paramount — the Upaniṣads are the primary means of knowing Brahman, which cannot be perceived or inferred by the ordinary mind.',
    ontology: 'Advaita: Brahman alone is real; the world and individual selves are Brahman appearing through māyā. Viśiṣṭādvaita: Brahman (Viṣṇu) is the one reality with selves and matter as real but inseparable modes. Dvaita: Brahman (Viṣṇu) is fundamentally and eternally distinct from selves and the world.',
    soteriology: 'Mokṣa through Brahman-knowledge (Advaita), bhakti culminating in direct experience of Viṣṇu (Viśiṣṭādvaita / Dvaita). The nature of liberation differs: for Advaita it is identity with Brahman; for Dvaita it is eternal loving service in Vaikuṇṭha.',
    tenets: [
      { label: 'Brahman', body: 'The ultimate reality. Described as sat-cit-ānanda (being-consciousness-bliss). Whether Brahman is nirguna (without qualities, Advaita) or saguna (with qualities, Viśiṣṭādvaita/Dvaita) is the central debate.' },
      { label: 'Ātman-Brahman', body: 'The relation between individual self (ātman/jīva) and Brahman. Advaita: identical (tat tvam asi). Viśiṣṭādvaita: inseparable-different (viśiṣṭa). Dvaita: eternally distinct (bhedavāda).' },
      { label: 'Māyā / Avidyā', body: 'For Advaita, māyā is Brahman\'s power by which the one appears as many. Avidyā (ignorance) is the cause of bondage. Viśiṣṭādvaita rejects māyā as illusion; Dvaita rejects it entirely.' },
      { label: 'Jñāna-mārga', body: 'The path of knowledge — typically associated with Advaita. Śravaṇa (hearing the mahāvākyas), manana (reflection), nididhyāsana (meditative absorption) progressively dissolve the illusion of separateness.' },
      { label: 'Bhakti-mārga', body: 'Foregrounded by Rāmānuja and Madhva. Devotion to Viṣṇu/Kṛṣṇa is not subordinate to jñāna but is itself the highest path, leading to the direct vision of the Lord and eternal communion.' },
      { label: 'Prasthānatrayī', body: 'The three textual foundations of Vedānta: the Upaniṣads (śruti), the Brahma Sūtras (nyāya-prasthāna), and the Bhagavad Gītā (smṛti-prasthāna). Each ācārya writes commentaries on all three to establish their school.' },
    ],
    commentators: [
      { name: 'Śaṅkarācārya', period: '~8th c. CE', work: 'Brahmasūtrabhāṣya', note: 'Advaita Vedānta: Brahman is the sole reality; all duality is māyā. The most influential philosophical synthesis in Indian intellectual history.' },
      { name: 'Rāmānuja', period: '~11th–12th c. CE', work: 'Śrībhāṣya', note: 'Viśiṣṭādvaita: Brahman (Viṣṇu) is one, but with selves and matter as real, inseparable modes. Systematises bhakti within a rigorous philosophical framework.' },
      { name: 'Madhvācārya', period: '~13th c. CE', work: 'Brahmasūtrabhāṣya', note: 'Dvaita Vedānta: Five eternal distinctions — Brahman/jīva, Brahman/matter, jīva/jīva, jīva/matter, matter/matter — are absolutely real.' },
      { name: 'Vallabhācārya', period: '~15th–16th c. CE', work: 'Anubhāṣya', note: 'Śuddhādvaita: Brahman (Kṛṣṇa) is pure, the world is real Brahman-transformation, and puṣṭi-mārga (grace-path) leads to eternal vraja-bhakti.' },
    ],
    pairNote: 'Vedānta builds directly on Mīmāṃsā\'s hermeneutic methods while rejecting its ritual-primacy. Śaṅkara\'s debates with Mīmāṃsā interlocutors — and Maṇḍana Miśra\'s bridge position — mark the decisive philosophical junction.',
  },
]

export const MATRIX: MatrixRow[] = [
  {
    topic: 'Ultimate reality',
    nyaya: 'God + plural selves + matter',
    vaisheshika: 'Plural substances (9 dravyas)',
    samkhya: 'Puruṣa + Prakṛti (dualism)',
    yoga: 'Puruṣa + Prakṛti + Īśvara',
    mimamsa: 'Eternal Veda + plural selves + matter',
    vedanta: 'Brahman (Advaita: non-dual; others: theistic)',
  },
  {
    topic: 'Nature of the self',
    nyaya: 'Eternal, plural, non-conscious substance',
    vaisheshika: 'Eternal, plural, non-conscious substance',
    samkhya: 'Pure consciousness (Puruṣa), plural',
    yoga: 'Pure consciousness (Puruṣa), plural',
    mimamsa: 'Eternal, conscious, plural agent',
    vedanta: 'Ātman — identical with / mode of / distinct from Brahman',
  },
  {
    topic: 'God / Īśvara',
    nyaya: 'Accepts — efficient cause, proven by inference',
    vaisheshika: 'Accepted (later) as cosmic coordinator of atoms',
    samkhya: 'Rejected (nirīśvara)',
    yoga: 'Accepted — special Puruṣa, meditation object',
    mimamsa: 'Rejected — Veda is self-authorising',
    vedanta: 'Advaita: Brahman = Īśvara; Rāmānuja/Madhva: Viṣṇu as supreme Lord',
  },
  {
    topic: 'Theory of knowledge',
    nyaya: '4 pramāṇas: perception, inference, comparison, testimony',
    vaisheshika: '2 pramāṇas: perception and inference',
    samkhya: '3 pramāṇas: perception, inference, testimony',
    yoga: '3 pramāṇas + yogic perception (pratyakṣa)',
    mimamsa: '6 pramāṇas — adds postulation and non-cognition',
    vedanta: '3 pramāṇas — śabda (Upaniṣad) is primary',
  },
  {
    topic: 'Liberation',
    nyaya: 'Apavarga — cessation of pain (negative state)',
    vaisheshika: 'Mukti — cessation of misidentification with body',
    samkhya: 'Kaivalya — isolation of Puruṣa from Prakṛti',
    yoga: 'Kaivalya — through citta-vṛtti-nirodha',
    mimamsa: 'Dharmic fulfilment; later: apavarga through correct ritual',
    vedanta: 'Mokṣa — identity with / proximity to Brahman',
  },
  {
    topic: 'World / matter',
    nyaya: 'Real, atomic, created by God',
    vaisheshika: 'Real, atomic, eternal (atoms), God coordinates',
    samkhya: 'Real transformation of Prakṛti (pariṇāmavāda)',
    yoga: 'Real transformation of Prakṛti (same as Sāṃkhya)',
    mimamsa: 'Real, eternal matter; world is real',
    vedanta: 'Advaita: apparent (vivartavāda); others: real transformation',
  },
  {
    topic: 'Vedic authority',
    nyaya: 'Valid as testimony (śabda) from an omniscient God',
    vaisheshika: 'Accepted as valid verbal testimony',
    samkhya: 'Accepted as āptavacana (testimony of reliable persons)',
    yoga: 'Accepted; Īśvara is teacher of the Veda',
    mimamsa: 'Highest — eternal, self-authorising, primary source of dharma',
    vedanta: 'Highest — Upaniṣads are the means of Brahman-knowledge',
  },
  {
    topic: 'Advaita sub-school',
    nyaya: '—',
    vaisheshika: '—',
    samkhya: '—',
    yoga: '—',
    mimamsa: '—',
    vedanta: 'Advaita (Śaṅkara) · Viśiṣṭādvaita (Rāmānuja) · Dvaita (Madhva)',
  },
]
